# Generated by Django 4.2.6 on 2023-10-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Valor')),
                ('dt_created', models.DateTimeField(verbose_name='Data de criacao')),
            ],
            options={
                'verbose_name_plural': 'Vendas',
                'ordering': ['-dt_created'],
            },
        ),
    ]
