# Generated by Django 4.2.6 on 2023-10-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturometro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='painel',
            field=models.IntegerField(choices=[(1, 'DO CAMPO À MESA'), (2, 'SHOPPING COMPRE DO PEQUENO')], default=1, verbose_name='Painel'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='dt_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de criacao'),
        ),
    ]
